[modules]
    core = ["bootstrap", "fontawesome"]
    optional = ["mermaid"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex","mermaid"]
    [modules.mermaid]
        state = "defer"
    [modules.fontawesome]
        inline = true
        debug = true
        skipMissing = false
    [modules.utils]
        filter = "[^0-9A-Za-zŽžÀ-ÿ ;.,\\/'’\"]-"
        raw = false   

[debugging]
    showJS = true
    showSCSS = true