[modules]
    optional = ["mermaid"]
    disableTemplate = ["mermaid"]
    [modules.mermaid]
        state = "defer"
        elk = true
        layout = "elk"
        look = "classic"

[debugging]
    showJS = true
    showSCSS = true
