baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-mermaid'

[module]
  replacements = 'github.com/gethinode/mod-mermaid -> ../..'
  # Build and serve using local mod-mermaid clone declared in the named Hugo workspace:
  workspace = "mod-mermaid.work"
  [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/gethinode/mod-mermaid"
