baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-mermaid'

[module]
  # Build and serve using local mod-mermaid clone declared in the named Hugo workspace:
  workspace = "mod-mermaid.work"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-mermaid/v3"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v4"
